# Generated by Django 4.0.6 on 2022-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('material_1', models.TextField()),
                ('material_2', models.TextField()),
                ('material_3', models.TextField()),
                ('material_4', models.TextField()),
                ('material_5', models.TextField()),
                ('material_6', models.TextField()),
                ('material_7', models.TextField()),
                ('material_8', models.TextField()),
                ('material_9', models.TextField()),
                ('material_10', models.TextField()),
            ],
        ),
    ]
